# Generated by Django 5.2.8 on 2025-12-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowances',
            field=models.ManyToManyField(blank=True, to='core.allowance'),
        ),
    ]
