# Generated by Django 5.2.9 on 2025-12-08 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attendancedevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='allowances',
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allowance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'unique_together': {('employee', 'allowance')},
            },
        ),
    ]
