# Generated by Django 5.2.9 on 2025-12-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_create_employeeallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowances',
            field=models.ManyToManyField(blank=True, through='core.EmployeeAllowance', to='core.allowance'),
        ),
    ]
