# Generated by Django 5.2.9 on 2025-12-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_employee_allowances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowance',
            name='amount',
        ),
    ]
