# Generated by Django 5.2.9 on 2025-12-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employee_user_hrprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='da',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hra',
        ),
    ]
