# Generated by Django 5.2.9 on 2025-12-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_holiday_leave_salaryadvance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Casual Leave, Medical Leave', max_length=100, unique=True)),
                ('days_allowed', models.PositiveIntegerField(help_text='Total days allowed per year for this leave type')),
            ],
        ),
    ]
