# Generated by Django 5.2.9 on 2025-12-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='no_break',
            field=models.BooleanField(default=False),
        ),
    ]
