# Generated by Django 5.2.9 on 2025-12-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_attendance_no_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='esi_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
