# Generated by Django 5.2.9 on 2026-01-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_employee_esi_number_employee_pf_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
