# Generated by Django 5.2.9 on 2026-01-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_attendancelock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancelock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancelock',
            name='date',
            field=models.DateField(blank=True, help_text='Specific date for day-level lock. If null, it represents a month-level lock.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendancelock',
            unique_together={('employee', 'date', 'month', 'year')},
        ),
    ]
