# Generated by Django 5.2.9 on 2026-01-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_attendancelock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
